language: node_js

node_js:
  - 14.13.0

# PR branches will be built as PRs.
branches:
  only:
    - master

build:
  cache: true
  env:
    # Set environment variable for test results output
    - XUNIT_FILE=shippable/testresults/result.xml
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/node_modules
  ci:
    - npm install
    - npm test

integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - acit-sys-apps@maillist.ox.ac.uk
        - miguel.pellicer@ctl.ox.ac.uk
      on_success: change
      on_failure: change
      on_cancel: change
      on_start: never
      on_pull_request: never
  generic:
    - integrationName: canvas-where-am-i-github
resources:
  - name: canvas-cpn-weekly-trigger
    type: time
    versionTemplate:
      #interval: "0 0 * * MON"  # this field accepts cron like syntax
      interval: "0 * * * *" # This is for testing purposes, test the automatic build every hour.

jobs:
  - name: canvas-cpn-weekly-tests
    type: runSh
    steps:
      - IN: canvas-cpn-weekly-trigger
      - TASK:
          name: Unpack build artifact onto public S3 bucket
          script:
            - git clone https://github.com/oxctl/canvas-where-am-i
            - cd canvas-where-am-i
            - npm install
            - npm run test-deployed
